/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.module.gradle;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.util.Comparator;
import java.util.Map;
import java.util.TreeMap;

public class App {
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    public static void main( String[] args )
    {

        Map<String, String> myName = new TreeMap<>(Comparator.reverseOrder());
        myName.put("lastName", "Kiiashchenko");
        myName.put("name", "Alex");
        System.out.println(GSON.toJson(myName));

    }
}
